### ISSUE TITLE
Confirm before navigating away from unsaved data

### ISSUE THREAD

**Issue by michaeljwilliams** [Paratron/hookrouter#10]
Just finishing integrating hookrouter into my current project. I like it a lot so far! Very easy to implement and reason around.

On a certain page my user is filling out a form, and I want to confirm before they can leave, to prevent loss of unsaved data.

I think it would be better if this was baked into the package somehow. I'd want something simple where you could set it for a whole page and it applies to children and parents. I also would prefer to be able to pass any function, in case window.confirm() isn't good enough.

**Comment by Paratron** [comment]
Whats wrong with this approach?

```jsx
if(confirm('Are you sure?')){
    navigate('/somewhereElse');
}
```

**Comment by Paratron** [comment]
Ah, you mean that you also want to prevent navigation by clicking on a link. I will make up my mind about that.

**Comment by michaeljwilliams** [comment]
To use that, none of the links on the page could be <A />s. They'd have to be regular elements with an onClick={your code}. That would be really tedious to do if I had a bunch of links on the page. And it would be impossible for links in another component.

**Comment by Paratron** [comment]
I made a concept about how this could be implemented. This would also enable us to do some kind of conditional URL rewriting... Not sure about it, tough - I need to let it sink in.

```jsx
import {useInterceptor} from 'hookrouter';
// Random form stuff
import {saveData} from 'dataStuff';
import {MyForm} from '../forms';

const myInterceptor = (nextPath, currentPath) => {
	if(confirm('Do you really want to leave?')){
		return nextPath;
	}
	return currentPath;
};

const GuardedForm = () => {
	const stopInterception = useInterceptor(myInterceptor);

	const handleSubmit = (data) => {
		saveData(data);
		stopInterception();
		navigate('/somewhereElse');
	}

	return (
		<MyForm onSubmit={handleSubmit} />
	);
}
```

A interceptor function is being called after a navigation intention has been made through either clicking an `<A>` tag or calling `navigate()`.

The next path and the current path is passed to the interceptor and it may decide about the path to return. Whatever path the interceptor returns gets the new path to navigate to. If the interceptor returns the same path as the current path, nothing happens.

This would also give the possibility to "lock" just parts of the URL. For example you want to split up an input process about several sub-parts of the url but prevent the user from navigating away from the process as a whole, you could do it with an interceptor.

__Example:__ Allow navigation between `/register/general`,  `/register/photo` or `/register/details` but not to `/otherPage`.

**Comment by FredyC** [comment]
I don't think this will suffice. Navigation is not always explicit through the link, but the user can simply hit back button in the browser and this solution would not prevent that. Also sometimes it's useful to warn about unsaved data before closing a browser window, sometimes it's being closed by a mistake.

That's why I was suggesting integration with [`history`](https://www.npmjs.com/package/history) package. Why to reinvent the wheel?

**Comment by Paratron** [comment]
I think I was not clear enough - the interceptor gets called on a _navigation intent_. Navigation intents can be triggered through link clicks, calls to `navigate()`, clicking back/forward in the browser.

Hookrouter is right now about 1.8kb in size. The history package alone would add ~3kb - just for one function that I can implement by adding a couple of lines of code. This does not justify installing such a dependency. Those need to outweigh the drawbacks of adding dependencies by far.

**Comment by FredyC** [comment]
Ok, fair enough. It's kinda nice thinking out of the box indeed :)

One more thing with `useInterceptor`, would be really lovely if we could actually render React components when the intercept happens. The `confirm` can suffice for some simple stuff, but some apps want to use a custom modal.

**Comment by Paratron** [comment]
Well, by moving the intercept function into the react component function, it will be able to access state properties and setters. Then, you could actually tell the component that and which route has been intercepted and react on it:

```jsx
import React from 'react';
import {useInterceptor} from 'hookrouter';
// Random form stuff
import {saveData} from 'dataStuff';
import {ConfirmPopup} from '../popups'
import {MyForm} from '../forms';

const GuardedForm = () => {
	const [interceptedRoute, setInterceptedRoute] = React.useState(null);
	const myInterceptor = React.useCallback(
		() => (nextPath, currentPath) => {
			setInterceptedRoute(nextPath);
			return currentPath;
		},
		[setInterceptedRoute]
	);
	const stopInterception = useInterceptor(myInterceptor);

	const confirmedNavigation = () => {
		stopInterception();
		navigate(interceptedRoute);
	}

	const handleSubmit = (data) => {
		saveData(data);
		stopInterception();
		navigate('/somewhereElse');
	}

	return (
		<div>
			{ interceptedRoute && <ConfirmPopup onConfirm={confirmedNavigation} /> }
			<MyForm onSubmit={handleSubmit} />
		</div>
	);
}
```

**Comment by Paratron** [comment]
This is too complicated. I think I will simply add another hook next to `useInterceptor()` - namely `useControlledInterceptor()` which does the above automatically but is much simpler to use:

```jsx
const SimpleGuardedForm = () => {
	const [interceptedRoute, setInterceptedRoute] = React.useState(null);
	const [stopInterception, confirmNavigation] = useControlledInterceptor(setInterceptedRoute);

	const handleSubmit = (data) => {
		saveData(data);
		stopInterception();
		navigate('/somewhereElse');
	}

	return (
		<div>
			{ interceptedRoute && <ConfirmPopup onConfirm={confirmNavigation} /> }
			<MyForm onSubmit={handleSubmit} />
		</div>
	);
}
```

**Comment by FredyC** [comment]
That looks great, definitely much easier than with `react-router` for sure :) Once this and #11 is resolved, I am seriously considering the switch. Great job man!

**Comment by michaeljwilliams** [comment]
> One more thing with `useInterceptor`, would be really lovely if we could actually render React components when the intercept happens. The `confirm` can suffice for some simple stuff, but some apps want to use a custom modal.

That’s why I was suggesting being able to pass a callback function when intercept is called.

**Comment by michaeljwilliams** [comment]
I'm getting an error while trying to use `useInterceptor`. I cloned the repo and ran `prepublishOnly` and imported `useInterceptor` in my component. I copied the interceptor code from your test file. Now when my app compiles and I go to that route, I get this error:

![image](https://user-images.githubusercontent.com/10594600/55100907-2d721d00-5080-11e9-918a-042994916c42.png)

**Comment by FredyC** [comment]
@michaeljwilliams I highly recommend https://github.com/whitecolor/yalc tool for installing unreleased packages. I did it already and works just fine for me. Haven't tried `useInterceptor` yet, but seeing it's exported correctly, it's more likely wrong on your side.

Also, note that with CRA it won't be able to load newly added (or updated) library from `node_modules`. You have to restart the process.

**Comment by michaeljwilliams** [comment]
@FredyC I got it worker using yalc; thanks for the advice. I used the following to make the app behave as expected (warns whenever trying to navigate away, if you confirm then it proceeds). I like this!

```javascript
const stopInterception = useInterceptor((currentPath, nextPath) => {
    if(window.confirm("Are you sure you want to leave without saving?")) {
        stopInterception();
        navigate(nextPath);
    }
})
```
