### ISSUE TITLE
Route state

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#11]
Sometimes it's useful to have an additional state within the navigation intent, but it might be bulky and more structured than what URI is providing.

https://github.com/Paratron/hookrouter/blob/9d52bc2b89ad5e00d9c44dd646db0686d5dcee3b/src/router.js#L45

Would be lovely if we could specify state object instead of having a fixed `null` there.

Then there is a matter of how to consume it. I think it can be the second argument to the route callback. Some contrived example follows.

```jsx
const routes = {
    '/': () => <HomePage />,
    '/products/:id': ({id}, { type }) => <ProductDetails id={id} type={type}  />
};
	
const handleClick = () => {
    navigate('/products/12', { type: 'main' });
};
```

**Comment by Paratron** [comment]
I am really not sure about this. My belly tells me that the state should be managed in React/Redux and not in the browser history. Googling how you would do this in React Router also shows some really messy solutions. Even the [StackOverflow question about whats the purpose of state objects](https://stackoverflow.com/questions/17612307/pushstate-what-exactly-is-the-state-object-for) in browser history doesnt give good examples.

I fear implementing such a mechanism that closely tied to the most basic building blocks of hookrouter invites for misuse through users.

**Comment by FredyC** [comment]
Sure, it's not like I am using it often, but sometimes it happens. The main difference is that such state is tied to that exact navigation intent. If you go back in history or even refresh a browser, that state is there. If it would be solved on an app state level, it's fairly risky to run into some unexpected behavior.

**Comment by FredyC** [comment]
Ah, I see now why you do not want to implement it. It clashes with API of #1. Makes sense that query params are probably more common than route state. I will try to figure if I can live without it or eventually fork the lib.
