### ISSUE TITLE
React.StrictMode stops navigation from working (since version 1.2.0)

### ISSUE THREAD

**Issue by jmrfrosa** [Paratron/hookrouter#115]
Hey,
It seems navigation is not working when `useRoutes` is within `<React.StrictMode>`. I'm fairly new to both React and routing, so I'm not sure if this is somehow intended, but it was really confusing to figure out why running the documented code pasted on an app created with `create-react-app` was not working as intended.

Sample code: https://codesandbox.io/s/hookrouter-strictmode-problem-ozy72

Toggling `hookrouter` versions also seems to show that this behaviour only started happening after v1.2.0.

**Comment by dreddi** [comment]
same issue, using hookrouter@1.2.3

**Comment by Paratron** [comment]
Not happening anymore in 2.0
