### ISSUE TITLE
Old QueryParams Maintained on Browser Back Button Click

### ISSUE THREAD

**Issue by GeocelinJ** [Paratron/hookrouter#116]
When navigate back using Browser Back Button, old QueryParams maintained in useQueryParams.

Example :

I have two pages. Page-1 , Page-2

Page-1 : 
const [queryParams] = useQueryParams(); // It gives {} ,since it doesn't has queryparams 
...
navigate('/page2',false,{'name' : 'john'}); // navigate to page 2

Page-2 : 
const [queryParams] = useQueryParams(); // {'name' : 'john'} gave queryparams.

Now Clicking Browser Back Button , I am navigating to Page 1.
Here 
const [queryParams] = useQueryParams();
result would be {} // empty. But I am getting {'name' : 'john'}

If I am missing anything , Please correct the same.

Thanks..

**Comment by Paratron** [comment]
Not present anymore in 2.0
