### ISSUE TITLE
Popstate Event Handler calls pushstate even when location.pathname === currentPath

### ISSUE THREAD

**Issue by agevry** [Paratron/hookrouter#118]
It seems that if a popstate event is received that a history.pushState() call is done even if the location.pathname === currentPath. This is causing an infinite loop in a project I am working to add hookrouter to as it uses synthetic popstate events.

I have a fix which I will submit which just adds a check to see if location.pathname !== currentPath before calling the pushState().

**Comment by Paratron** [comment]
Obsolete for 2.0

**Comment by agevry** [comment]
Any date regarding when we can expect 2.0?  I'm working towards converting sections of a large application and would like to use hook router but would feel a lot more comfortable using either 1.x with a fix in it for this issue or 2.x.  I can patch it during webpack building but that's a little hacky.
