### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#12]
@Paratron I assume you are not TypeScript user, but many TS users would appreciate having types available.

The best course of action is, of course, have the source in TypeScript. It can compile to clean JS a similar way as Babel can. Or you can even use Babel to compile and TypeScript to extract typings only.

Otherwise, it means to manually synchronize types for every API change.

I can help with either way.

**Comment by Paratron** [comment]
I will absolutely and never ever change this project to TypeScript. I am a strong opposer to using TypeScript at all.

If anyone thinks, this project needs typings he/she is free to contribute to the [@types](https://github.com/types) collection.

**Comment by FredyC** [comment]
Such hostile tone was unnecessary 😕 It was a legit question. If you dislike it so much, it's your choice, but there are people loving. It's almost a question of religion...

Cool beans, I will just make types for my use and possibly share in here. I don't like DefinitelyTyped ecosystem.

**Comment by danawoodman** [comment]
Man, this is unfortunate... If anyone has the time to do the type defs, that would be amazing!

In the meantime, you can create a file `hookrouter.d.ts` and include:

```ts
declare module 'hookrouter'
```

... to suppress errors but it won't get you any type checking.

**Comment by mcaneris** [comment]
I have created types for this package. 

Linking pull request to DefinitelyTyped for those interested: [#35443](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35443)

**Comment by Paratron** [comment]
Thanks for creating the dype definitions - I will mention them in the README.
