### ISSUE TITLE
hash param support in navigate.

### ISSUE THREAD

**Issue by jgoergen** [Paratron/hookrouter#122]
If I added hash params support in navigate, would you be interested in pulling that in? Or is there a fundamental reason why you've omitted that?

**Comment by Paratron** [comment]
Yes, because I didn't deem that necessary. Version 2 will have the possibility to implement a hash based router provider, if someone needs that.

**Comment by jgoergen** [comment]
I ended up needed it in one case, I don't mind helping if you have anything you'd want help with, though!
