### ISSUE TITLE
External url navigation

### ISSUE THREAD

**Issue by Mrbeyond** [Paratron/hookrouter#125]
Navigation to external url address or domain not working. Example the anchor <a href='https://google.com' ></a> or naviagte('https://google.com') does not route to the external url but keeps matching the pathname to the Internal routes. Please I really need help with this. Thanks in advance.

**Comment by Paratron** [comment]
Hm, what did you expect? Calling `navigate()` passes an URL fragment to the router to match it. Its not supposed to get passed full urls with domain and everything.

Why don't you place a traditional ´<a>` tag, if you want to create a link to another domain?

**Comment by Mrbeyond** [comment]
Thanks a lot For the reply.
I actually did mention the  normal
<a href='https://google.com>google</a>
where I wrote  anchor and it surprising now that it's not there. It could
be a typing issue, please pardon my mistake.

I tried the normal <a> tag several times but it was the same effect because
normally if I use <a> tag to replace the hookrouter <A> Component, the
result is the same by navigate to the desired route. It just occurred to me
right now that such could happen if the <a> and <A> performs the same thing.
Please I really need the feature Sir.

**Comment by Paratron** [comment]
Okay, wait a sec. If you import the `<A>` component from hookrouter, that would not work with external URLs, because it passes everything to `navigate`.

If you want to create a link to another website, use the `<a>` component instead!

**Comment by Mrbeyond** [comment]
I am totally confused because it's not navigating to another website even with <a> tag but only tries to match the href to the routes and if none is found the not found page declared is rendered.  Can I share the code now please?

**Comment by Paratron** [comment]
You should have been provided a code example on codesandbox.io in the first place so I can give any help at all :)

**Comment by Mrbeyond** [comment]
Thanks a lot Sir.

While preparing the sandbox sample, I've got to know the issue. The issue
is the addition of http:// or https:// before the actual URL like
https://the-desired-url, else it will see it as internalized route link
even if <a> tag is used. If the href start with "/" it will try to find the
matching route else it will concatenate the href to the current route.
Thanks for your quick reply and helping mind Sir.

In addition I think it will be good to have the list of sites using the
hookrouter in the documentation and I'll be glad to include the one I'm
working on as well, so as to increase its awareness and I'm huge fan and
ambassador of hookrouter due to its simplicity.

**Comment by Mrbeyond** [comment]
The is resolved.

**Comment by dschinkel** [comment]
Someone really needs someone to update the docs then.  I assumed <A> would also redirect not only to paths, but external urls.
