### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Paratron** [Paratron/hookrouter#13]
I need to create proper documentation - at best using a tool like docusaurus.

**Comment by FredyC** [comment]
Are you open to PR or you want to do that by yourself? I was just recently thinking I would like to try setup docusaurus for some project, but have no relevant candidate.

**Comment by Paratron** [comment]
I am currently playing around with different doc solutions. I am not sure if docusaurus fits here, it adds too much fluff around the docs, imho.

**Comment by FredyC** [comment]
Ok, up to you, let me know if you decide for docusaurus eventually.
