### ISSUE TITLE
Typescript Support.

### ISSUE THREAD

**Issue by Aslemammad** [Paratron/hookrouter#136]
I fell in love with this tool, but something hookrouter needs, and that is typescript support. I can take a PR and convert the all of the project to Typescript. Any opinion? ♥️😘

**Comment by robpearmain** [comment]
That sounds great

**Comment by Aslemammad** [comment]
So, Thanks, I take the PR?

**Comment by Aslemammad** [comment]
In Readme.me they wrote that they won't write in TS. So  I close this issue.
