### ISSUE TITLE
Feature: Generated navigation functions

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#14]
Just an idea, needs some thinking through. What I've always missed with `react-router` is some DRYness in route paths and navigation. We have various paths floating all around and it's easy to miss one in case of some change because it's just a string.

For example, when I specify `/products/:id` in routes, it would be great to somehow get a function bound to such route. Instead of repeating that string, I would like to call something like `navigateProducts({ id: 11 })`.

Perhaps it's more of a job for some code generator tool than a runtime solution. Mainly because it would be lovely to have types for such calls (sorry @Paratron).

**Comment by Paratron** [comment]
While I encourage this way of working, I don't think it needs to be baked into the module directly. Hook router is flexible enough that you can compose your route objects at will - you can import them from other modules. So it is certainly a good idea to have a central navigation module that exports functions like:

```jsx
export const showProductPage = (productId) => navigate(`/product/${productId}`);
```

This adds much more clarity to your code and you cannot make mistakes with routes (or need to change routes all over your project when you want to change a path).

**Comment by FredyC** [comment]
Ok, makes sense I guess. I will eventually have a look at some code generation option, that would make it much easier.

**Comment by Paratron** [comment]
Yeah, its just like with redux. The basic package is very simple but flexible. There are additional modules you can install to help you generating actions, selectors, etc.
