### ISSUE TITLE
Feature: Static route for testing purposes

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#15]
In a couple of automated tests, we need to set the current route so it renders what's expected based on the current route.

I suppose it's as easy as exposing a function that modifies closest context value. It could be tricky in regards to nested routing though because tests don't include the whole App, but only a portion of it.

**Comment by Paratron** [comment]
In a node context you can use the to-be-documented method `setPath()`. Testing frontend features would require to mock `history` and `location`. Maybe its better to fire up a static server and go over the test app with cypress.

**Comment by FredyC** [comment]
> Maybe its better to fire up a static server and go over the test app with cypress.

Sure, that works in most cases. But sometimes there is a route driven logic in the component when I don't want to be prop drilling some route parameters.

> Testing frontend features would require to mock `history` and `location`

I believe that's already part of the `jest-environment-jsdom`, so that should be fine.
