### ISSUE TITLE
Feature: Relative navigation

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#16]
There is a [long-standing discussion](https://github.com/ReactTraining/react-router/issues/5127) in `react-router` about this. I haven't read a whole thing, it's back and forth in there. So I am wondering if some thinking out of the box can be applied to the hooks solution. 

The basic idea is that you can call eg. `navigate('../')` to simply move higher in a hierarchy relative to a current path.

Relative routes are a different story and I wouldn't worry about that right now.

**Comment by Paratron** [comment]
You can do that already.

**Comment by FredyC** [comment]
Ah, so lack of the documentation only? Awesome :) Closing and linking #13 as a reminder there.

**Comment by Paratron** [comment]
Well, I was not aware that this is an issue in React Router. If you have an <a> tag with href = `../`, the browser will do a relative navigation. That is already _build into_ the browser. Also if you do `history.pushState(null, null, '../')`, the same thing happens. I did not feel the necessarity to document that :D

**Comment by FredyC** [comment]
Geez, so what are those guys talking about in that mega thread? 🤣 I will definitely try it later and reopen if I run into some issues.
