### ISSUE TITLE
Feature: Replace instead of push

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#17]
I see that `navigate` will always push, but sometimes it's required to navigate by replacing.

For example route `/product/new`, when the form is saved, I would like to replace history with eg. `/product/15` and then navigate with a push to `/products`. In case the user goes back, he should go to the created product page and not to create a new one again.

To make this happen it's either about introducing `navigateReplace` as a separate function or perhaps wrapping the second argument of `navigate` to some options. Honestly, I don't think that query params are that common to have such a prominent place there.

```js
navigate('path', { replace: true, queryParams: {...}})
```

**Comment by Paratron** [comment]
Whoa whoa whoa, hold back for a second.

If you are on route `product/new` and hit the "save" button on your form, you will fire a request to the backend, create your object, will receive it in the frontend and then will _of course_ navigate forward to `product/[id]`. Why would you want to replace the history entry. This would mean that you do _not_ navigate but just mutate the url. 

The example you made is invalid. There is no need to do a replacing navigation. A regular website would not work like that, either.

**Comment by FredyC** [comment]
Our UX is about navigating back to the list of products after creating it. Even if I would do forward navigation to a path with a new ID, we don't have there a direct link to a product list. A user needs to go back in history. That means he would be navigating from `/product/15` back to `/product/new` and then he would need to navigate back again to get to the list.

Don't blame me for UX choices, I did not make them :)

**Comment by FredyC** [comment]
Btw, there are surely other cases for replacing logic. Some temporary pages which you don't want a user to get back again because it would not make any sense. For example, some confirmation page after the important operation that shows summary which is too bulky to show in the modal. Letting user navigate back to such page can break stuff for sure.

**Comment by grahammendick** [comment]
@Paratron You really should take my [router challenge](https://github.com/grahammendick/router-challenge). It has a [good replace use case](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md#selecting-an-album)

**Comment by Paratron** [comment]
@FredyC I think you are right. Let me think over the necessary API changes.

@grahammendick As I already replied in the other issue:I dont have time for that. Please implement that by yourself if you have such a desire to see it done. It doesnt belong into this issue thread.

**Comment by Paratron** [comment]
I just implemented the feature. I came to an interesting point and think that I will change the default behaviour of the `useRedirect()` hook to replace. 

The reason is, if I have a route `/about` and navigate to `/` but there is an automatic redirect from `/` to `/whatever`, I will never be able to get from `/whatever` back to `/about` because navigating back from `/whatever` would take me to `/` which would immediately forward me to `/whatever` again. This would not happen if the redirect would utilize history replace instead of push.

**Comment by FredyC** [comment]
Well, are you sure it's really necessary to have those `queryParams` as a second argument? Any replacement call will awkwardly look like `navigate('path', null, true)`. I would even say it's terrible because it's not apparent from the first look what is that doing and you need to check the documentation on that matter.

Personally, I will definitely end up with `navigateReplace` wrapper, but I am really curious why are you against options object. Not only it gives names to those arguments, but it's much more flexible if more options are needed in the future.

**Comment by Paratron** [comment]
I am not actually against it, but in 99% of all cases you will call `navigate()` only with an url and nothing more. Hm. I need to think about it.

**Comment by sant3001** [comment]
I would also vote for having a way to use replace instead of push 👍

**Comment by FredyC** [comment]
@sant3001 It's already there, it's just rather awkward API: `navigate('path', null, true)`

**Comment by Paratron** [comment]
Not quite, I changed the argument order. Its now `navigate(path, replace, queryParams)`

**Comment by FredyC** [comment]
So it will look like `navigate('path', true)` ... slightly better, but you still have no clue about what that `true` means in there. No worry, I will wrap it for myself, obviously `options` are a too big problem for you ;)
