### ISSUE TITLE
[Feature Request] Regex route match

### ISSUE THREAD

**Issue by eslachance** [Paratron/hookrouter#21]
It would be lovely to have more power in the routing path. Mainly I'm thinking regex, to acheive effects similar to [express-router](https://expressjs.com/en/guide/routing.html).

Here's a few examples: 

```js
const routes = {
    '/': () => <HomePage />,
    '/ab+cd': () => <Alphabet />,
    '/ab(cd)?e': () => <ProductOverview path={$1} />,
    /a/: () => <ProductDetails id={$1} />
};

**Comment by Paratron** [comment]
I would love to have RegEx routes. The problem is that we cannot use a regular expression as a key in an object. Maybe we can use a string representation, but I am not quite sure if I like that style:

```jsx
const routes = {
    'regex:/ab+cd^/g': () => <MyComponent />
};
```
Do you have a practical use case for this?

**Comment by FredyC** [comment]
Not that I can think of any use case for it, but an alternative would using the `Map` construct which can have anything as a key. Although it would be a slightly different and unusual syntax with key-pairs.

```js
const routes = new Map([
  [/ab+cd^/g, () => <MyComponent />],
]);
```

**Comment by eslachance** [comment]
As a use case, here's an example. I have a route that allows for a product to be requested. 

If the product is an ID (1-10 digits), pull the ID from a table and show the product
If the product is a slug (something-like-this-using-regex), lookup the slug first then show using that ID
If the product doesn't match regex, ignore it so it goes to 404.

Quick & dirty example, but this is more efficient than, say, actually going *into* the route itself, then having to do conditions on regex matching and database lookups, then have to duplicate the 404 response if they're not found. Or one could have different pages shown depending on different regex matches, etc. 

To be fair, if you want syntax people recognize, might as well consider the possibility of adding a manual `addRoute` method where we can add a regex on the left and the return function on the right. Y'know, just like Express and Koa do it, because people are very familiar with that idea when it comes to routing.

**Comment by FredyC** [comment]
@eslachance Are you sure something like that needs to be handled on routing level? What about this?

```js
const routes = {
    '/product/:id': ({ id }) => {
      if (isSlug(id)) {
        return <SlugProduct slug={id} />
      }
      return <Product id={id} />
    }
};
```

Sure, it's less _declarative_, but seems easy enough and ultimately way too powerful.

**Comment by eslachance** [comment]
Wait are you saying the router doesn't support async behaviour? (I know this is a different conversation, but I'm really curious)

**Comment by FredyC** [comment]
Ummm...I don't think so :) The `react-router` does not support it either AFAIK. Not that it would be impossible, but the amount of uses cases is probably not that big to be worth it.

You can easily have a component like this...

```jsx
const navigateToProduct = (id) => {
  navigate(`/product/${id})`
}
const ProductLoader = ({ id }) => {
  React.useEffect(() => {
    if (isSlug(id) {
      fetchIdFromSlug(id).then(navigateToProduct)
    } else {
      navigateToProduct(id)
    }
  }, [id])
}
```

**Comment by eslachance** [comment]
Well no, react-router doesn't do it, but if react-router was _good_, we wouldn't need alternatives like hookrouter now would we? ;)

You should take a look at Koa for inspiration, not react-router ;)

**Comment by Paratron** [comment]
Wow, lots of comments while I was at work :D

@eslachance No, the router is not async. In fact, you don't even _want_ it to be. Your UI needs to respond immediately, even if async operations happen after a routing. At least you want to show a loading indicator.

For example, if you want to lazy-load additional components, this pattern works great with synchronous routing:

```jsx
const ProductEditor = React.lazy(() => import('./ProductEditor'));

const routes = {
    'productEditor/:id': ({id}) => (
        <React.Suspense fallback="Loading...">
            <ProductEditor id={id} />
        </React.Suspense/>
    )
}
```

**Comment by Paratron** [comment]
In case of the difference in id/slug and your products, I would suggest a different architectual approach. Your product component does not need to care about the backgrounds of how the product data is actually gathered. It should only show the product - so for example:

```jsx
const routes = {
	'/product/:id' => ({id}) => <Product id={id} />
};

const Product = ({id}) => {
	const [product, status] = useProduct(id);

	if(status.loading){
		return 'Loading...';
	}

	if(status.error === 404){
		return <NotFoundPage />;
	}

	return (
		<div className="productDetails">
			<h1>{product.title}</h1>
			<p>
				{product.description}
			</p>
		</div>
	);
};
```

Now you can move the whole logic about how to fetch product data - based on id, slug or whatever - into a separate function (`useProduct()`). The component doesnt care anymore. Thats the true power of hooks 😎

**Comment by eslachance** [comment]
You're right, I was approaching the issue from the angle. Still, regex routes would be super bae if you can figure out how to do them ;)

**Comment by Paratron** [comment]
I thought a lot about regex routes in the last days and I think they don't make it for now. At first I thought the idea was cool, too but I am afraid it adds unnecessary complexity to the routes.
