### ISSUE TITLE
Feature: Use IDs for paths and navigation

### ISSUE THREAD

**Issue by krizka** [Paratron/hookrouter#22]
In one router there were feature to set each route an ID, so later you can use `<A to="some-id">Go to ID</A>`, So, if topology of routes changed, you no need to change links all over the code.
Every time I started new project, thinking about this great feature. What do you think?

**Comment by FredyC** [comment]
I think this is perfectly doable in userland. It's merely about some kind of mapping between routes and ids.

Either way, I don't feel it's such a great feature, you are basically exchanging one string for another. In my opinion, a much better way is something I was proposing in #14 to have it hidden in named functions so whenever the need for change comes, you will be at least getting runtime errors and not just silent failures. With static typing, it won't even compile.

**Comment by krizka** [comment]
Agree, it also denies dynamic routing, because we can not know all IDs before they will be rendered and defined.
