### ISSUE TITLE
Repeated unknown route does not trigger changes

### ISSUE THREAD

**Issue by pickypg** [Paratron/hookrouter#27]
While writing up a standard 404 page, I noticed an interesting behavior where if I navigate to a 404 page, it works as you would expect. However, if you try to navigate in-app from there to another page that _also_ triggers the 404 route, then nothing is triggered.

This causes confusing state, especially if you use `window.location.pathname` in the 404 component.

Fortunately this is not a very realistic scenario in most webapps, but it's very easy to notice while building out a new one.

**Comment by Paratron** [comment]
Yeah, hookrouter does internal route caching. If the outcome does not change, the receiving react component will not be updated.

I think in case of a non-match we can make an exception here. 🤔

**Comment by timraybould** [comment]
How about when I'm trying to navigate from `/products/1` to `/products/2`? The URL changes, but how do I get the component to update?

**Comment by Paratron** [comment]
If your route is `/products/:id`, your component will be updated since the url parameters changed.

**Comment by timraybould** [comment]
That's my route, yes. The issue was I forgot to put "id" in the array that's passed as the second argument to useEffect. Thanks. Hookrouter is great so far, btw!

**Comment by timraybould** [comment]
Another question on this. Is there a way to force an update to the component?

On a particular route, my app has the ability to open a menu (modal window). Whether or not this menu is visible is a simple flag which I store in the state of the parent (layout) component and pass down to the child (the one associated with the route). When I click "X" within the child, the menu goes away, but I also need to be able to dismiss the menu via a click in the main nav, aka in the parent (layout) component.

If I reference the child component directly from the parent, this all works fine. But if instead I reference the child component via a `routeResult`, then the child will not update when, even though the state on the parent (the layout component) changes, because the route has not changed.

**Comment by Paratron** [comment]
Please don't misuse this issue comment section for general purpose questions about how to use hook router.

There is no way to force an update to a component. What I would advise in your case is the pattern is applying [the following pattern](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/02_routing.md#passing-additional-data-to-route-functions).

**Comment by Paratron** [comment]
@pickypg I updated the routing function so it triggers an update whenever the route result is `null`. Released in `1.1.4`.

Can you tell me if this solves the problem for you?

**Comment by timraybould** [comment]
Apologies. I thought it was related enough to not open a new issue and not merely "general purpose." I think when people search the issues log for "does not trigger changes" many of them will have a question similar to mine and thus having it here might save you some support work.

"No way to force an update" is helpful, thank you. Also, I might be able to use the "update when route result is null" outcome of this thread to help solve my particular use case.

**Comment by Paratron** [comment]
No worries, I just try to keep the comment threads clean. Did you try my pattern, I mentioned above? You do not need to re-evaluate the route directly, you just want to pass new data to your child component, if I got you right..

**Comment by timraybould** [comment]
Now we're really going to get off topic :)

I tried/failed to understand that pattern. I think what's happening is the route is "hit" which triggers a function which returns _another_ function which then returns a component with new props. If that's correct, I think I got lost by not understanding where the variable 'product' was coming from.

Anyway, I think I've solved it by adding the menu state as a new route. So now it's `/product/menu` when the menu is open and closing it triggers plain old '/product`. The downside is some potentially counter-intuitive things with the browser's back button, but passing `true` as second argument to `navigate()` I think has smoothed that out.

**Comment by pickypg** [comment]
@Paratron Your change did not seem to be enough. Usage example:

```js
const unknownRoute = () => {
  console.log('Routed to unknown: ' + Date.now());

  return Date.now();
}

return useRoutes({
  '/': () => 'root',
  '/sub': () => 'sub',
}) || unknownRoute();
```

The time only changes on the first reroute given `null`.

@timraybould It would probably be clearer to open a separate issue.

**Comment by pickypg** [comment]
@Paratron Just as an FYI, this is still an issue in 1.1.6 (in case it got lost in the unrelated discussion).

**Comment by Paratron** [comment]
Hey @pickypg I made a compromise. The route will still remain static, but you can use the [new hook `usePath()`](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/04_other-features.md#using-the-uri-path) to tap into the current URI path name.

Tell me if this helps with your issue!

**Comment by pickypg** [comment]
Assuming it works as documented, then this should work perfectly. :)

Thanks!
