### ISSUE TITLE
Navigate back

### ISSUE THREAD

**Issue by timraybould** [Paratron/hookrouter#29]
Is there a way to navigate back one place in the browser's history?

**Comment by timraybould** [comment]
Ah, never mind, using "window.history.go(-1)" works just fine.

**Comment by Paratron** [comment]
To be honest, I did not include a navigate-back solution on purpose. Its a bad UX pattern. The browser back button should only be used by the user. You should always do forward navigation so your user can go back by himself.

**Comment by dy** [comment]
Back does not mean undo browser history, back means add previous path to browser history.

There are cases sometimes when that is needed, like, back button in [evergreen-ui](https://evergreen.segment.com/components/layout-primitives): if we have adjacent-page transition, then back button should go back, not to the root.

**Comment by jonotann** [comment]
I 100% agree it's bad UX when referring to desktop applications,

But when using ReactJS as a Web Application on Mobile, when added to a home screen the ability to back out on most modern devices is not available. Not a super big deal to manually implement but definitely to be considered.
