### ISSUE TITLE
Write Tests

### ISSUE THREAD

**Issue by Paratron** [Paratron/hookrouter#3]
I definitely need to create tests before this can be moved out of beta. I used it in a couple of customer projects right now and it seems to work fine, but tests are mandatory 💪

**Comment by FredyC** [comment]
In case you haven't discovered yet, I would highly recommend https://www.npmjs.com/package/react-hooks-testing-library

**Comment by rardoz** [comment]
I wouldn't mind helping out with writing tests.

**Comment by Paratron** [comment]
I started to implement some kind of integration test - its basically a small app/site that uses the router and its functionalities. No styling, just plain HTML and navigation.

The question is - should we still add unit tests where possible, or is the integration test enough.

**Comment by FredyC** [comment]
I think that the difference between integration and unit test in case of this lib is very minimal because hooks can be seen as units and as a feature as well. I would even say that making an app/site is more on the side of E2E testing. Integration tests can be done with Jest as well. That lib is a big help in that.

**Comment by rardoz** [comment]
Thats a good question @Paratron. Would the integration test have a coverage report we can see? If so, then I think that should be enough. I started to write some unit tests using jest and enzyme. So far I just have the A component tested, so I haven't gotten too far on it.

**Comment by rardoz** [comment]
Thinking about SSR, having integration tests might be the better approach.

**Comment by Paratron** [comment]
I think its better if you hold back for now. I am implementing SSR and a new `useQueryParams()` hook and am rewriting parts of the library which might invalidate your tests.

**Comment by Paratron** [comment]
Okay, I built some quick and dirty test app into the repo for manual testing but I think we are better off, if we have some automated testing in the future.

I would be glad if someone could take over the task of creating proper tests - I will be busy creating proper docs in the next days.

**Comment by pickypg** [comment]
As part of #25, I implemented some unit tests. It may be useful to use that / modify it to move forward. I believe automated tests are extremely useful too because people will get lazy and simply not run through the entire test app.
