### ISSUE TITLE
Rerender onpopstate

### ISSUE THREAD

**Issue by dy** [Paratron/hookrouter#30]
Could you pls showcase example how to rerender screen when user navigates browser history? Would be really nice use-case coverage. For now browser history does not seem to affect hookrouter.

**Comment by Paratron** [comment]
Huh, what do you mean? If the user clicks the back/forward buttons in his browser, hookrouter reacts to the URL updates.

**Comment by dy** [comment]
Hm. Ok, apparently something's wrong with my app.

**Comment by Paratron** [comment]
Looks like your app is fine. I found some cases where I also get strange behaviour when navigating backwards/forward in history. I will investigate.

**Comment by Paratron** [comment]
Okay, should be fixed, now 👍 
Published in `1.1.5`
