### ISSUE TITLE
Proposed improvements for setting query params

### ISSUE THREAD

**Issue by webakimbo** [Paratron/hookrouter#37]
1) Ideally, `setQueryParams` would merge rather than replace existing query params:

**Current:**
start URL: `/?animal=dog`
action: `setQueryParams({ name: 'fido' })`
end URL: `/?name=fido`

**Proposed:**
start URL: `/?animal=dog`
action: `setQueryParams({ name: 'fido' })`
end URL: `/?animal=dog&name=fido`

2) An empty query object might trim the `?` from the URL:

**Current:**
start URL: `/`
action: `setQueryParams({})`
end URL: `/?`

**Proposed:**
start URL: `/`
action: `setQueryParams({})`
end URL: `/`

**Comment by Paratron** [comment]
You are right, I already had a similar thought recently but forgot to write it down.

The only thing that becomes weird is unsetting parameters. But I thing setting them to `undefined` to remove them should be fine.

**Comment by webakimbo** [comment]
IIRC, setting a param to undefined already unsets it?

**Comment by Paratron** [comment]
You are right - I completely forgot about the unsetting. 😅 

I made an example for the case - looks like this is a bug in the serialization function. Internally, the param object remains fine: https://codesandbox.io/embed/p33w1pzwk7?module=/src/app/index.js

**Comment by Paratron** [comment]
Fixed and released in `1.1.6`
