### ISSUE TITLE
Securing routes

### ISSUE THREAD

**Issue by nojaf** [Paratron/hookrouter#38]
This is more of a question but what I want to secure a route? F.ex check if the user has a certain claim or something.

Would the following be a good approach:

```jsx
import React, { useState, useEffect } from 'react';
import {useRoutes, A, navigate } from 'hookrouter';

const HomePage = () => {
  return (
    <div>
      HomePage
    </div>
  );
};

const AboutPage = () => {
  return <div>About</div>
}

const NotFoundPage = () => {
  return <div>Not found</div>
}

const UnAuthorized = () => {
  return <div>Unauthorized</div>
}

const Secure = ({children}) => {
  const isAuthorized = false; // imagine checking an Auth token.
  useEffect(() => {
    if(!isAuthorized){
      navigate(`/unauthorized`)
    }
  });

  return children
}

const routes = {
    '/': () => <HomePage />,
    '/about': () => <Secure><AboutPage /></Secure>,
    '/unauthorized': () => <UnAuthorized />
  };

const App = () => {
  const routeResult = useRoutes(routes);
  
  return {routeResult || <NotFoundPage />
}

export default App;
```

Is this approach a good practise? Or is there something better out of the box for this?

**Comment by Paratron** [comment]
Well, out of the box there is nothing built into hookrouter to secure paths. You would need to validate by your own logic if a user is actually allowed to visit a certain route.

I personally would have used a hook function instead of a component wrapper for checking the authorization but thats a matter of taste :)

By the way: you don't have to stuff the call to `navigate()` into a hook. The [redirect hook](https://github.com/Paratron/hookrouter/blob/master/src/redirect.js) doesn't do it either.

**Comment by nojaf** [comment]
> I personally would have used a hook function instead of a component wrapper for checking the authorization but that's a matter of taste :)

And then call that hook in each component that needs securing? I'd prefer to have that in one place. Unless I'm misinterpreting this here.

> By the way: you don't have to stuff the call to navigate() into a hook. The redirect hook doesn't do it either.

```jsx

const Secure = ({children}) => {
  const isAuthorized = false; // imagine checking an Auth token.
    if(!isAuthorized){
      navigate(`/unauthorized`)
    }
  return children
}
```

Like this?

**Comment by Paratron** [comment]
Well, either you have sprinkled parts that need authentication across several routes, then you need to check authentication on all those places. Or you wrap all authenticated pages into a namespace in your URLs and have a central component controlling the auth. For example:

With this code, calls to `/welcome` or `/login` would not require authentication while `/authed/user` or `/authed/posts` would require authentication that is handled in a cental component.

```jsx
// Main Component, showing all routes

const routes = {
	'/welcome': () => <WelcomePage />,
	'/login': () => <Login />,
	// Everything authenticated is handled in here.
	'/authed*': () => <AuthedPages />
};

const myApp = () => {
	const result = useRoutes(routes);
	return result || 'Not found';
};

// ===========================================================
// Component handling all authenticated requests.
// ===========================================================

const authedRoutes = {
	'/user': () => (authData) => <UserPage />
	'/posts': () => (authData) => <UserPosts />
	'/settings': () => (authData) => <SettingsPage />
};

const AuthedPages = () => {
	const authData = useAuthentication();
	const routeResult = useRoutes(authedRoutes);

	if(!authData){
		navigate('/login');
	}

	return routeResult(authData);
}
```

**Comment by nojaf** [comment]
Thanks, that helped!

**Comment by acnebs** [comment]
> I personally would have used a hook function instead of a component wrapper for checking the authorization but thats a matter of taste :)

The problem with this solution is that if you want to have any additional hooks between the auth hook and the return of the PFC, those hooks will try to execute, which maybe you don't want if the user isn't authed.

**Comment by krtk6160** [comment]
> Well, either you have sprinkled parts that need authentication across several routes, then you need to check authentication on all those places. Or you wrap all authenticated pages into a namespace in your URLs and have a central component controlling the auth. For example:
> 
> With this code, calls to `/welcome` or `/login` would not require authentication while `/authed/user` or `/authed/posts` would require authentication that is handled in a cental component.
> 
> ```js
> // Main Component, showing all routes
> 
> const routes = {
> 	'/welcome': () => <WelcomePage />,
> 	'/login': () => <Login />,
> 	// Everything authenticated is handled in here.
> 	'/authed*': () => <AuthedPages />
> };
> 
> const myApp = () => {
> 	const result = useRoutes(routes);
> 	return result || 'Not found';
> };
> 
> // ===========================================================
> // Component handling all authenticated requests.
> // ===========================================================
> 
> const authedRoutes = {
> 	'/user': () => (authData) => <UserPage userId={authData.userId} />
> 	'/posts': () => (authData) => <UserPosts userId={authData.userId} />
> 	'/settings': () => (authData) => <SettingsPage userId={authData.userId} />
> };
> 
> const AuthedPages = () => {
> 	const authData = useAuthentication();
> 	const routeResult = useRoutes(authedRoutes);
> 
> 	if(!authData){
> 		navigate('/login');
> 	}
> 
> 	return routeResult(authData);
> }
> ```

I receive an error saying `TypeError: routeResult is not a function`
