### ISSUE TITLE
Add getWorkingPath to exports

### ISSUE THREAD

**Issue by rardoz** [Paratron/hookrouter#40]
I have a case where I need to know the route I'm on from within a component down the tree. I see that `getWorkingPath` is exported in the router but not in the exports from hookrouter. Could we add this to the exports?

**Comment by Paratron** [comment]
Yes, I have already a pull request for that purpose. I just need to review if the function call behaves correctly in all cases. For example, in nested routes, it would only return the nested path, not the full path.

**Comment by Paratron** [comment]
Okay, maybe this helps you with your issue!

I found the `getWorkingPath` being too unreliable (and it also executes more logic that is only relevant for the routing internals).

I just implemented [a new hook called `getPath()`](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/04_other-features.md#using-the-uri-path) that returns the current URI path name the application is working with as string. Hopefully this helps you in your case!
