### ISSUE TITLE
forwardRef on A

### ISSUE THREAD

**Issue by tograd** [Paratron/hookrouter#42]
Component libraries ([material ui](https://next.material-ui.com/guides/composition/#caveat-with-refs) for example) and people most likely want/require to reference the native element rather than the wrapper component

Should be changeable without any breaking changes probably (but check out: https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers)

**Comment by Paratron** [comment]
I would suggest creating a [custom link component](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/03_navigation.md#creating-custom-link-components) in that case. Its easy to do, you can use refs or whatever you want to and I don't have to implement any arcane voodo which is not needed in most cases.

**Comment by tograd** [comment]
I don't think forwardRef is arcane voodoo but I think your solution is fair. Cheers
