### ISSUE TITLE
navigate() ignores query params

### ISSUE THREAD

**Issue by asin90** [Paratron/hookrouter#43]
According to the [documentation](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/03_navigation.md):

> // These are the same
> navigate('/test?a=hello&b=world');
> navigate('/test', false, {a: 'hello', b: 'world'});

However the above is not true. First example navigates to '/test' and the second example navigates to '/test?a=hello&b=world'

**Comment by asin90** [comment]
Another unexpected behaviour is that navigate() includes the params from the current path, for e.g:
Given that we're on the path:
 **'/path?currently=here**
`navigate('/to', false, {a: 'hello', b: 'world'});`
will navigate to:
**/to?currently=here&a=hello&b=world**
But I'm expecting:
**/to?a=hello&b=world**

**Comment by Paratron** [comment]
The first one is a bug. I am not sure why it doesnt (need to investigate), but `navigate('/test?a=hello&b=world');` should work.

The second one is an effect of how the `useQueryParams()` hook works - it appends parameters instead of replacing them. But I think when calling `navigate()` the behaviour should be replace instead of append.

**Comment by Paratron** [comment]
I updated the behavior of `navigate()` in the `1.2.0` release. URL params will now be replaced by default. 

Excerpt from the docs:

Please note that if you do a navigation with query parameters, old query parameters will be dropped. This is unlike the default behavior of useQueryParams, where parameters will be appended. If you would like your query parameters to be appended upon navigation, pass `false` as fourth argument (`replaceQueryParams`): `navigate('/test', false, {...}, false)`.

Also note that if you do a navigation with query parameters already encoded into the URI, useQueryParams hooks _won't be updated_!

**Comment by asin90** [comment]
Great work & thank you for your effort! :)

My second issue seems to be solved, however the [first](https://github.com/Paratron/hookrouter/issues/43#issue-434107794) is not - the below is still not true:

> // These are the same
navigate('/test?a=hello&b=world');
navigate('/test', false, {a: 'hello', b: 'world'});

**Comment by knightjdr** [comment]
I'm using 1.2.3 and can confirm that manually entering query parameters as in the example still causes navigation to `/test`

```
navigate('/test?a=hello&b=world');
```
