### ISSUE TITLE
usePath alongside useRoutes

### ISSUE THREAD

**Issue by pickypg** [Paratron/hookrouter#48]
This is an example of my router code, which is pretty basic:

```tsx
  // If no route is found, always send them to UnknownPage
  return useRoutes(routes) || <UnknownPage />;
```

The `routes` object is currently rather trivial. The problem occurs with the new `usePath` hook used within the `UnknownPage` component.

Within the `render` method of that component I fetch and display the `path`:

```tsx
// UnknownPage
render() {
  const path = usePath();

  // rendered a little prettier, but logically:
  return (
    <>404 Unknown page: {path}</>
  );
}
```

This triggers this error:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

Of interest, if I move the `usePath` hook usage outside of the `useRoutes` code path, then everything is happy, but it also means every sub-component is getting rerendered unnecessarily.

**Comment by Paratron** [comment]
Hm, while I _did_ test the `usePath()` hook, I did not test it in a sub component... I will try to recreate the situation and figure out whats wrong 👍

**Comment by Paratron** [comment]
Works like a charm for me...

But I noticed something. You mentioned above "within the render method". Hooks can only work in functional components. If you use a class based component (which has a render method), hooks do _not_ work.

**Comment by pickypg** [comment]
Ah, that's it! I didn't realize that that was a limitation of hooks. Making my `UnknownPage` a functional component that passes in the `usePath` value into a subcomponent worked like a charm. Thanks!
