### ISSUE TITLE
Do not prevent default behavior of link if Ctrl is pressed

### ISSUE THREAD

**Issue by Onatolich** [Paratron/hookrouter#49]
Currently if you will click on link with Ctrl pressed new tab won't be open because default behavior is prevented.

**Comment by Paratron** [comment]
You are correct and I support that!

More things came to my mind. What, when you focus the link using the tab key and then pressing enter? Thats not even a click. What if some browsers/oses do things different on ALT+click? I need to think this through for a bit. Sadly there is no such thing like a navigate event for a link, so those cases need to be handled separately.

I guess it boils down to "only prevent default when a left mouse button click (or tap) happens without any modifier key pressed" and "prevent default on keyboard enter/space hit".

Phew.

**Comment by Paratron** [comment]
This is resolved with `1.2.2` and available on npm now.
