### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [Paratron/hookrouter#5]
It's not healthy for the Router market to be so dominated by the React Router. I want to level the playing field so that your Hook Router gets a fair crack of the whip. That's why I've written the [Router Challenge](https://github.com/grahammendick/router-challenge). It aims to do for Routers what TodoMVC did for UI frameworks by offering the same SPA built in React using different Routers. For it to be successful I need your help. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the SPA using your Hook Router, please?

**Comment by Paratron** [comment]
I am afraid that I don't have enough free time for this.
