### ISSUE TITLE
[Feature]: Wildcard Redirect

### ISSUE THREAD

**Issue by cevr** [Paratron/hookrouter#50]
How difficult would it be to implement a wildcard redirect?

So instead of having to write 6 redirects, it would be similar to this:
```js
function Component() {
  useRedirect('*', '/login')
  //...
}
```
Some problems I can think of is that this might overwrite routing that is already mapped, so some route checking will be required.

**Comment by Paratron** [comment]
Wait, you want to redirect _everything_ to `/login`? 😱

The redirect hook does nothing else than performing an if-case and call `navigate()`. Would that be an acceptable case for you to do by yourself?

**Comment by cevr** [comment]
Yes that's true,

The use case was for if a session were to expire while the web-page is open, any subsequent request will cause the the app to become unauthenticated, recreating the route object. They would be then redirected back to their previous page prior to being logged out so to speak. The wildcard would make it a bit easier, rather than mapping every path.

**Comment by Paratron** [comment]
How about this pattern? You can secure components that need auth this way:

```jsx
const MyPageWithAuth = () => {
  return isAuthenticated() && (
    <div>
      <h1>Hey!</h1>
      <p>
        You can see this only when logged in.
      </p>
    </div>
  );
}
```

The `isAuthenticated()` function is implemented like this:

```jsx
const isAuthenticated = () => {
  const authCondition = /* depends on you */;
  const currentPath = usePath(false); // Set to passive, because we don't need to watch path changes

  if(!authCondition){
    navigate('/login', false, {returnTo: currentPath});
    return null;
  }
  return true;
};
```

If we are for example trying to access `/private`, this logic would forward the user to `/login?returnTo=/private`. Its easy to grab the query param using `useQueryParams()` and forward the user back to the page where they came from.

Does this sound reasonable?

**Comment by cevr** [comment]
@Paratron This seems like an easy enough pattern. Thanks for the timely responses!

**Comment by Paratron** [comment]
Glad I could have helped! I think I need to start collecting those patterns... :D
