### ISSUE TITLE
Support for URL hash?

### ISSUE THREAD

**Issue by danawoodman** [Paratron/hookrouter#52]
Is there a way to support URL hash change instead of route change like React Router? I have a need to use hash instead of path for routing because I'm building an electron application which is served at `/index.html` and isn't served by a web server, so route change doesn't work properly. Is this possible to support as a configuration?

**Comment by wmertens** [comment]
@danawoodman if you don't reload the page, all the URL changes are just virtual, no? So they should still work?

**Comment by Paratron** [comment]
I am not sure I understand the problem. In an electron app, the URL is hidden from the user, so the user is not able to jump directly into a specific URL or refresh the page or something like that.

Why do you need to use hash based routing in that environment? I can understand you would need it when you have a backend that is incapable of url rewriting but thats not the case for an electron app.

**Comment by Paratron** [comment]
But to answer your question: no, its currently not possible to use hashes for navigation.

**Comment by danawoodman** [comment]
I wanted to use URL routes to manage what components to render when a user navigates. Also, I wanted to eventually package this application to work in the browser without an electron backend. 

Thanks for the answer, I've removed hookrouter and made my own navigation behavior instead. Cheers 👍

**Comment by rardoz** [comment]
Would be great to have this! Don't know why the issue is closed.

**Comment by wmertens** [comment]
@rardoz why would this be great? Can't you use paths?

**Comment by rardoz** [comment]
This breaks HTML's link jumping / bookmark feature. Check out this example: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_links_bookmark

See more on how this works under the HTML Links - Create a Bookmark section of this page:
https://www.w3schools.com/html/html_links.asp

**Comment by wmertens** [comment]
@rardoz yes, that's exactly why you normally route with the path and not with the query?

**Comment by rardoz** [comment]
I got this working by using a normal anchor tag vs the hook router one A component. ;)

**Comment by konsumer** [comment]
Yeh, I have the same problem in electron. 

```js
const routes = {
  '/': () => <PageHome />,
  '/media/:id': ({ id }) => <PageMedia id={id} />,
  '/live': () => <PageLive />
}

const Main = () => {
  const routeResult = useRoutes(routes)
  console.log('RESULT', routeResult)
  return routeResult
}
```

I get `RESULT null`

**Comment by konsumer** [comment]
`window.location` looks like this:

```json
{
  "href": "file:///home/konsumer/Documents/projects/test/src/index.html",
  "ancestorOrigins": {},
  "origin": "file://",
  "protocol": "file:",
  "host": "",
  "hostname": "",
  "port": "",
  "pathname": "/home/konsumer/Documents/projects/test/src/index.html",
  "search": "",
  "hash": ""
}```

I can make it work with these terrible URLs:

```js
const routes = {
  '/home/konsumer/Documents/projects/test/src/index.html': () => <PageLive />,
  '/home/konsumer/Documents/projects/test/src/media/:id': ({ id }) => <PageMedia id={id} />,
  '/home/konsumer/Documents/projects/test/src/src/live': () => <PageLive />
}
```
