### ISSUE TITLE
customPath should not be a singleton

### ISSUE THREAD

**Issue by wmertens** [Paratron/hookrouter#53]
By making the `customPath` be a singleton in module scope, SSR can not be asynchronous and detecting redirects is harder.

I think it would be prudent to add the path to the Context and inject it at the top of the tree when doing SSR. That way each tree has its own private path and keeping track of redirects is easy

**Comment by Paratron** [comment]
Thanks for the thorough SSR review. Your points are valid and I will make plans on how to implement them!

**Comment by Paratron** [comment]
Obsolete in 2.0
