### ISSUE TITLE
queryParams does not work for SSR

### ISSUE THREAD

**Issue by wmertens** [Paratron/hookrouter#55]
queryParams uses a singleton to manage listeners, so this will easily leak if not unlistened, and it will cause query params of two different in-progress SSR runs to be mixed up

(also, the URLSearchParams it uses is not supported in IE at all, probably worth documenting that it needs a polyfill there)

**Comment by mitchellwarr** [comment]
I've just encountered the issue of my app not working on IE anymore. Finally tracked it down to this very issue. If you wont be fixing it any time soon, please add a message on the front page readme that IE11 is not supported

**Comment by wmertens** [comment]
@mitchellwarr 	you can use https://www.npmjs.com/package/url-search-params-polyfill right? What I normally do is something like

```js
// in some function that inits the app before it runs
if (!global.URLSearchParams) await import('url-search-params-polyfill')
```

That way, only the old browsers will have to pay the price of not being up-to-date. If the import is tiny Webpack might bundle it with the main bundle.

**Comment by mitchellwarr** [comment]
@wmertens Thanks for your help. Its all working now

**Comment by Paratron** [comment]
So this is actually two bugs. :)

I removed the original bug with the queryParams for SSR in 2.0 (coming in a few days).

I will add a note on how to import the polyfill for IE11 to the docs, thanks for the heads up!
