### ISSUE TITLE
Defer Route Transition to code split routes 

### ISSUE THREAD

**Issue by cevr** [Paratron/hookrouter#56]
I'm trying to think how waiting for a route to be fully loaded before mounting could be implemented. 

Any thoughts?

**Comment by Paratron** [comment]
I would implement it like this:

```jsx
import React from 'react';
import {useRoutes} from 'hookrouter';

import LoadingPlaceholder from './LoadingPlaceholder';

const Page1 = React.lazy(() => import('./page1'));
const Page2 = React.lazy(() => import('./page2'));
const Page3 = React.lazy(() => import('./page3'));

const routes = {
	'/': () => <Page1 />,
	'/about': () => <Page2 />,
	'/contact': () => <Page3 />
}

const MyApp = () => {
	const routeResult = useRoutes(routes);

	return (
		<React.Suspense fallback={LoadingPlaceholder}>
			{routeResult}
		</React.Suspense>
	);
};
```

Actually waiting is not in favor of the user in this case. The app would "freeze" until the next "pages" components are loaded. You should use suspense instead and actually tell the user: hey, we are loading something here.

**Comment by cevr** [comment]
Indeed but I was thinking of something like a loading bar that would appear within the previous route. Something like [this](https://frontarm.com/demoboard/?id=96005e9c-63b6-4844-a76a-d01b1d3fee51)

**Comment by Paratron** [comment]
Well, the call to `import()` returns a promise. What you could do is intercepting the navigation, show a loading bar and wait for the promise to resolve - then finalize the navigation intent.

**Comment by vermakartik** [comment]
can you provide an example implementation

> Well, the call to `import()` returns a promise. What you could do is intercepting the navigation, show a loading bar and wait for the promise to resolve - then finalize the navigation intent.
