### ISSUE TITLE
usePath state not updating when navigating with browser history

### ISSUE THREAD

**Issue by xuo** [Paratron/hookrouter#57]
Awesome library, really loving the different appraoch based on hooks!

I've ran into an issue where the usePath state doesn't seem to get updated when navigating with/through browser history.

Reproduction on a bare bones CRA setup: [https://codesandbox.io/s/usepathonpopstate-bug-el812](https://codesandbox.io/s/usepathonpopstate-bug-el812)

As far as i can tell, the `updatePathHooks` function just doesn't get called at the end of the `popstate` event listener.

**Comment by Paratron** [comment]
Fixed in version 1.2.3 - thanks for the PR!

https://codesandbox.io/s/usepathonpopstate-bug-gy0vh

Looks like I have simply forgotten the function call in the popstate event 🙈
