### ISSUE TITLE
Using object-hash to create internal id

### ISSUE THREAD

**Issue by kidkkr** [Paratron/hookrouter#6]
https://github.com/Paratron/hookrouter/blob/c1871c3bc6d15ba7f175d243e3ec24ef55b87730/src/router.js#L204-L209

at `useRoute(routeObj)` internal id created by random function.
I think it is good to use https://github.com/puleos/object-hash on routeObj.
This will guarantees the uniqueness of the id of each route object.

**Comment by Paratron** [comment]
I will not pull in a dependency that is ten times as large as my own project just to generate a unique id. Certainly not.

Right now, the uniqueness of Math.random() ist more than enough - it has enough entropy that no collisions will occur. Nobody uses millions of router components inside one app.

However, I will get rid of the current solution and implement an auto-incrementing ID mechanism which is also more performant than the current random/string/split approach. 

Avoid unnecessary dependencies! Avoid the javascript fatique. Thanks :)

**Comment by kidkkr** [comment]
I agree. I've found the helper functions above! thank you 👍
