### ISSUE TITLE
Know the currently active route

### ISSUE THREAD

**Issue by federico-paolillo** [Paratron/hookrouter#60]
Is there a way to know which route is currently active ?  

I would like to add a CSS class to an `A` if it links to the current route, something like you would do in Angular using [RouterLinkActive](https://angular.io/api/router/RouterLinkActive#description), is there something available to do that ?

**Comment by Paratron** [comment]
You can fetch the current path through the [`usePath()` hook](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/04_other-features.md#using-the-uri-path). With that information, you can create the functionality you want to use.

**Comment by federico-paolillo** [comment]
Do you think would make sense to include in hookrouter another hook called `useIsPathActive(path)` that would return `true` or `false` anytime the current path matches the path given ?  
If you think that would be useful I could make a PR for that

**Comment by Paratron** [comment]
I don't feel like implementing more code into the library just to save people from writing an if statement... But thanks for the offer :)
