### ISSUE TITLE
Entire app re-renders on route change

### ISSUE THREAD

**Issue by TrentWest7190** [Paratron/hookrouter#61]
Hi, I'm not sure if maybe I'm missing something simple, but is there any way to have your entire app not re-render when the route changes? I've tried wrapping my main App component in React.memo, but the issue still occurs.

**Comment by nojaf** [comment]
This sounds serious. Do you have anything to reproduce this?

**Comment by knightjdr** [comment]
It happens to me with CRA when running in development mode, but the production build doesn't have this problem. May be what the OP is seeing.

**Comment by Paratron** [comment]
It depends on how you have architectured your application. The component containing the hook call will (and has to) re-render on any route change (but not sub route changes).

If parts of your application should remain the same between routes, I'd suggest moving the `onRoute()` call forther down into a sub-component and leave the outer application frame out of the routing - however; I used both approaches (complete re-render vs. having routes moved into sub-components) without any major performance differences. As long as you are not navigating a lot (like every other second), no difference should be notable.

**Comment by StallionV** [comment]
It would be best if this is revisited.
Sometime you dont have an option but to place your Routing in App.js and load components based on that.
But what you also want is only the specific component to be loaded not the entire App.

Not having this ability and instead having to move the routing around in different places, could be a big hindrance in adaptability of the library and performance.
You really do not want to be rendering components again and again which have no relationship to the route.

Again the library is great, simple and is awesome when using hooks. But I am finding these drawback as we add more stuff to the application and having a rethink about using it, unless some of these issues are taken care of

**Comment by Paratron** [comment]
Wait, lets not mix things up here. You place a router hook in those components that you want to react to route changes. That is most certainly your top level component that reacts to root level changes like when you navigate from `/records` to `/artists` or something like that. Then again, you have child components that react to changes further down the URL, like a switch between `/records/1/details` and `/records/1/related`. 

As mentioned above, it depends on how you architecture your application. If you have just _one_ routing hook at the very top level for everything, it will make the whole app re-render upon each url change.

**Comment by Paratron** [comment]
> You may also want you routing to be in one place.

Nothing prevents you from defining a single javascript module where all routes are defined in. Export the different route objects from there and use them in the routing hooks inside your components.

I'd also recommend not to call `navigate('/records')` directly from your components, but create a function inside your routes module like this: `navigateToRecord(recordId)` - that abstracts the URL handling away for the application and its handled completely inside your routing module.

**Comment by StallionV** [comment]
> Wait, lets not mix things up here. You place a router hook in those components that you want to react to route changes. That is most certainly your top level component that reacts to root level changes like when you navigate from `/records` to `/artists` or something like that. Then again, you have child components that react to changes further down the URL, like a switch between `/records/1/details` and `/records/1/related`.
> 
> As mentioned above, it depends on how you architecture your application. If you have just _one_ routing hook at the very top level for everything, it will make the whole app re-render upon each url change and there is no way to work around that.

Thanks for the update. I only have top level routing and it means every-time my complete application re-renders.
How would you compare this to React Router then?

**Comment by Paratron** [comment]
I am not sure what you want to compare to react router here. If you place one router with routes at your application root level, react router would also cause your complete app to re-render upon route change, because you designed it this way. This is not related to the router you chose :)
