### ISSUE TITLE
Support reversible routing

### ISSUE THREAD

**Issue by lorefnon** [Paratron/hookrouter#65]
It would be nice if instead of compiling to regex this something like [route-parser](https://github.com/rcs/route-parser) could be used for reversible routing. 

This is advantageous in the sense that you get a function to construct routes, which fails cleanly when some parameters are missing (where as routes constructed through string interpolation would end up with undefined in the string) and also makes it unnecessary to refactor all route usages when the route patterns are to be changed.

**Comment by Paratron** [comment]
Area you able to give some clear examples? Based on your description, I have no idea what you mean.

**Comment by lorefnon** [comment]
Yes, I'll start with a slight modification of an example from the documentation: 

```js
const routes = {
    '/products/:id': ({id}) => <ProductDetails id={id} />
};

const MyApp = ({id}) => {
    const routeResult = useRoutes(routes);
    return (
        <div>
            <A href={`/products/${id}`}>Show my product</A>
            {routeResult || <NotFoundPage />}
        </div>
    );
}
```

Note that the dynamic url (`/products/${id}`) had to be constructed through string interpolation. This can result in something like `/products/undefined` if id is undefined. 

But a bigger issue is that if we decide to change that url, we would go need to hunt for usages all across the application which makes it likely to miss some urls, and the type systems or linters can't help us with adhoc string interpolations. 

If this were to support something like route-parser then the usage would look as follows: 

```js
import {Route} from 'route-parser';

const productRoute = new Route('/products/:id');

const routes = new Map()
    .set(productRoute, ProductDetails)
    .set(someOtherRoute, RoutePresenter);

const MyApp = ({id}) => {
    const routeResult = useRoutes(routes);
    return (
        <div>
            <A href={productRoute.reverse({id})}>Show my product</A>
            {routeResult || <NotFoundPage />}
        </div>
    );
}
```

Now if we decide to change the urls, then we can simply update the productRoute definition. 

If we are using typescript, then Route constructor is generic and and we change the route path to have additional paramaters (Say from `products/:id` to `departments/:departmentId/products/:id`) then we can simply change the generic paramaters and we will get type failures across all usages where `departmentId` was not being provided.

**Comment by wmertens** [comment]
I made https://gist.github.com/wmertens/edb55463dbddc4c8164580fb0b63a3ee to do something similar for react-router - it manages an object with all the parameters extracted from the current path, and it canonicalizes the path based on the object.

For creating a path for a route I actually just use helper functions that take the relevant data and return the URL. It's not as pure as reversible routes, but it gets you 95% of the way and you can actually deviate from the route. If you put all these helpers in the same file, it's easy to manage.

**Comment by Paratron** [comment]
Looking at the example above, this would severly impact the simplicity of usage of the library. I also don't like the heavy class based aproach of this.

The only real issue here - and I agree fully in that - is the in-place generation of URLs where you placed your links. This can get hairy real quick if you write a complex app. I suggest putting the routing object + functions that return URLs for the different routes inside one javascript module and just import that in your app. For example:

```jsx
export const routes = {
    '/products/:id': ({id}) => <ProductDetails id={id} />
};

/**
* Returns the URL for a product detail page.
* @param {string} id The id of the product to display.
*/
export const getProductURL = (id) => `/products/${id}`;
```

And to modify the example from above using this pattern:

```jsx
import {routes, getProductURL} from './routing';

const MyApp = ({id}) => {
    const routeResult = useRoutes(routes);
    return (
        <div>
            <A href={getProductURL(id)}>Show my product</A>
            {routeResult || <NotFoundPage />}
        </div>
    );
}
```

**Comment by wmertens** [comment]
@Paratron yes the BoundRoute is rather heavy, I wasn't suggesting it become part of hookrouter. I'd love thoughts about how to simplify it mind you - having canonical URLs is crucial in my app and there's quite a lot of values that are passed through the URLs.
