### ISSUE TITLE
Forcibly set location. Is this possible?

### ISSUE THREAD

**Issue by dmytro-shchurov** [Paratron/hookrouter#66]
May be requested feature is already available. But, I read docs and found nothing helpful.

With _react-router_ it's possible to setup a routing table in the following way

```jsx
<Switch location={previousLocation}>...</Switch>
{modal && <Switch>...</Switch>}
```

The purpose is to display a modal side panel alongside with a page that caused that panel sliding out.

**Comment by Paratron** [comment]
The route is always derived from the current url. This is by design. You cannot "force" a different route than the current url in any way.

However, you could use a query param to indicate that the panel should be shown, or give the page with the panel open its own real url. This way you could even send users to the application state with the panel open just by letting them follow the url.

**Comment by dmytro-shchurov** [comment]
I understand your point of view. However I think that urls like `/order/3?modal=/order/3/state` are a bit weird. 
Plus, modal windows are volatile by their nature. So, sending url with modal opened, for me, gives no benefits. 
Plus, such modals are glued to a particular page. You cannot define a route just to a modal panel, which can be opened from any page, which contains entity related to the modal panel content.
For instance, a panel that displays user info, could be opened from an order page, reservation page, user list page, roles page, etc...

**Comment by Paratron** [comment]
If there are no benefits of putting the modals open state into the url, then leave it completely out of it and move it to react state. You answered you own question :)

**Comment by dmytro-shchurov** [comment]
There is one reason. I left all boring component construction work for router. With *Route* component overrides I can specify desired layout declaratively in the table. But I would like to use urls and routes in a proper way (from my point of view).
And thank you that shared your thoughts.

**Comment by Paratron** [comment]
Well, you could do something similar for your modals. Basically the routing object you use for hookrouter has URLs as keys and functions that return components as values.

I would do something like that for a collection of modals - define an ID for each modal and put the modals component into the value. Then you could write your own hook in the top level component of your app that returns the modal component (if a modal is open) and you may have a function that allows you to open/close modals from anywhere in your app.

```jsx
// file: modalControl.js
import React from 'react';

const modals = {
	'login' => () => <LoginModal />,
	'user' => () => <UserModal />,
};

let currentModal = null;
const updaters = new Set();

export const useModal = () => {
	const [, setUpdate] = React.useState(0);
	React.useEffect(() => {
		updaters.add(setUpdate);
		return () => updaters.delete(setUpdate);
	} ,[setUpdate]);
	return currentModal;
};

export const setModal = (modalId = null) => {
	currentModal = modals[modalId]();
	const now = Date.now();
	updaters.forEach(cb => cb(now));
}
```

**Comment by dmytro-shchurov** [comment]
A-ha. So, this is like a combination of managing state of the topmost component (which is properly designed) and a "routing table". I have to try this. Thank you.
