### ISSUE TITLE
can not refresh

### ISSUE THREAD

**Issue by linchen2chris** [Paratron/hookrouter#67]
I navigate to a new page, then click refresh, can not render that page any more.
![refresh](https://user-images.githubusercontent.com/3970087/61019048-5f0eba00-a3cb-11e9-8c96-e808262bea1d.gif)

**Comment by kyeotic** [comment]
This is a problem with your server not having a route for `/content-detail`, its not a proble, with hooks router. Most people solve this with a server-side wildcard that renders the app

**Comment by Paratron** [comment]
This is not related to hookrouter but due to a faulty express setup.
