### ISSUE TITLE
Add a basename option

### ISSUE THREAD

**Issue by tttp** [Paratron/hookrouter#69]
Hi,
I'm using react with the dev and production version having a different base url.
I've worked around it with

```
basename = // based on .env
routes = {}
routes[basename + "/"]: () => <HomePage />,
...
and 	useRedirect('/', basename + '/wherever');

```

but was wondering if there is an option to set the basename, it feels more neat 

```
const routes = {
    '/': () => <HomePage />,
...
};

useRoutes(routes,basename);
```

**Comment by wmertens** [comment]
Can't you nest? And redirect to a relative path?

**Comment by wmertens** [comment]
I just found out about `setBasePath` https://github.com/Paratron/hookrouter/blob/c5002527b622400069cc783007ae9c765b7492ae/src-docs/pages/en/03_navigation.md#setting-a-base-path

**Comment by Paratron** [comment]
Like @wmertens noted, such a basepath option is already built into the library.
