### ISSUE TITLE
<A> and navigate(/path?query) strip off query

### ISSUE THREAD

**Issue by kyeotic** [Paratron/hookrouter#70]
According to #43 this was fixed, but it seems to have regressed. [This line](https://github.com/Paratron/hookrouter/blob/master/src/router.js#L38) uses `pathname` instead of the full route, ensuring `<A href='/path?key=value' />` routes to `/path`.

Having links that set query parameters is especially useful for pages with filters that need to be in the URL.

**Comment by romellance** [comment]
Yes, still an issue.

**Comment by kyeotic** [comment]
@romellance It seems this package is not being actively maintained anymore. I am actively maintaining an alternative: https://github.com/kyeotic/raviger
