### ISSUE TITLE
Query param interception

### ISSUE THREAD

**Issue by kyeotic** [Paratron/hookrouter#72]
In the [query param docs](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/04_other-features.md#using-query-parameters) it says
>Setting query params does not trigger a navigation intent. Query parameters are not used for routing in hookrouter.

Is this gap, not using query params for routing, _intended_ or merely the current state. I would like to be able to react query params as first-class route components, including for interception. I would happily make a PR for this if it would be welcome.

**Comment by Paratron** [comment]
Yes, this is intented. Only URLs are used for routing; query params are meant to be used to transmit additional data to a route.

**Comment by kyeotic** [comment]
I figured, but I wanted to ask. Since getting updates from query params is important to me, I built a similar router that does this. The API is clearly inspired by hookrouter, but I wrote all the internals from scratch.

https://github.com/kyeotic/wanderer/

**Comment by Paratron** [comment]
Just to get it right: if you have the following route: `"/mySearch": () => <SearchComp />` and inside `<SearchComp>`, you use the `useQueryParams()` hook to utilize the somehting like `/mySearch?q=whatevs` - the `SearchComp` component would be re-rendered any time the query params change. Isn't that exactly what you meant?

**Comment by Paratron** [comment]
Ah, you wanted to intercept query param updates as well - nevermind.

**Comment by kyeotic** [comment]
I have links that include query strings, and they dont cause hookrouter to rerender

**Comment by Paratron** [comment]
They should not cause the `useRoutes()` hook to re-render (since the route does not change), but thes _should_ cause the `useQueryParams()` hook to re-render, since the query params changed. 

I think your PR fixes that but I did not have the time to validate so far.

**Comment by kyeotic** [comment]
Should they cause `useQueryParams` to rerender even if they were set without using the set hook returned from `useQueryParams`? If so I think the rest of the issues can be fixed without the fork I made
