### ISSUE TITLE
closing a modal with the back button

### ISSUE THREAD

**Issue by rhyek** [Paratron/hookrouter#80]
Thanks for the great library. I'm trying to implement a modal dialog that closes if a user hits the back button (thinking about mobile devices). I've managed to implement the feature using `history.pushState` when opening the modal and then handling the `popstate` event to close it. The problem is when hitting the back button, after the dialog closes, any further clicks on the back button will not navigate backwards in history.

I have a sandbox here: https://codesandbox.io/s/hookrouter-modal-pushstate-df3wp

To test:
1) click on the "click me" link
2) click on the "show dialog" button
3) click on the sandbox's back button
4) click the back button again
5) here is the issue: the web view will not navigate back to the initial route

What changes can I make to my code to have this work? Thanks.

**Comment by rhyek** [comment]
I implemented this another [way](https://codesandbox.io/s/hookrouter-modal-pushstate-697ch) using actual routes for the modals without manipulating the route history and it's working fine so far, but there may come a time where doing it that way may not be possible/desirable, so I will leave this open for now in hopes of some feed back.

**Comment by Paratron** [comment]
This may be a matter of taste - but I would not solve it this way. If you want to have the dialog to be controlled via the URL, make it an actual part of the URL. If you want to control the dialog just through app logic, remember the state in a react state property.

There is an easy question if some logic should be handled through the URL: Do I want the user to be able to bookmark this page and/or open the view directly by opening a specific url.

The way you implemented it, no user would be able to open the dialog by calling the given url, so I would not tie the dialog logic against the router. But as I sayed: that may be a matter of taste.

**Comment by rhyek** [comment]
@Paratron the whole point is to be able to hit the physical back button on the phone and have it close the modal. This question is mostly why I opened this issue.

**Comment by Paratron** [comment]
Ah, I see. I think I would have solved it with creating an actual route for the dialog - and not relying on direct use of popstate/pushstate. So for example `/page` renders the page without dialog, while `/page/dialog` opens the page with dialog open. Than you can navigate back to `/page` at any time.

**Comment by rhyek** [comment]
That is what I implemented. When the modal is closed it is essentially a back action.. Still not sure about the best way to prevent the user from being able to click forward. It is actually a multi step flow and I would've liked to prevent the user to go back to the modals using back/forward buttons with invalid/outdated state.

**Comment by Paratron** [comment]
You could use a navigation interceptor, prevent the actual back navigation and then call `navigate('/page', true)` to replace the current state. 🙈
